"""add foreign key

Revision ID: 71850389a67a
Revises: 7808f8a75af5
Create Date: 2022-04-01 15:06:57.932230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71850389a67a'
down_revision = '7808f8a75af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('database', 'password_hash2')
    op.add_column('posts', sa.Column('poster_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'database', ['poster_id'], ['id'])
    op.drop_column('posts', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author', sa.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'poster_id')
    op.add_column('database', sa.Column('password_hash2', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
