"""added password field

Revision ID: 876080ffe7b4
Revises: 
Create Date: 2022-03-31 15:43:21.799194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '876080ffe7b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('database', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.drop_column('database', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('database', sa.Column('password', sa.VARCHAR(length=100), nullable=False))
    op.drop_column('database', 'password_hash')
    # ### end Alembic commands ###
