"""added password field

Revision ID: ce4700aa7410
Revises: 876080ffe7b4
Create Date: 2022-04-01 08:16:40.578902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce4700aa7410'
down_revision = '876080ffe7b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('database', sa.Column('password_hash2', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('database', 'password_hash2')
    # ### end Alembic commands ###
